version: '3.8'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.backend.env
      - ./.base.env
    ports:
      - "8000:8000"
    volumes:
      - temp:/usr/src/aaq_backend/temp
      - ../../backend/.gcp_credentials.json:/app/credentials.json
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - ./.backend.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432  # Expose the port to port 5434 on the host machine for debugging

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./.base.env

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - ./.base.env
    depends_on:
      - frontend
      - backend

volumes:
  temp:
  postgres_data:
  caddy_data:
  caddy_config:
