"""Add title, summary, bucket_link to DocumentDB

Revision ID: 2f85a60d67ab
Revises: 6a241a4af8da
Create Date: 2024-10-29 22:55:00.298252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f85a60d67ab"
down_revision: Union[str, None] = "6a241a4af8da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("title", sa.String(length=150), nullable=True))
    op.add_column("documents", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("pdf_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "pdf_url")
    op.drop_column("documents", "summary")
    op.drop_column("documents", "title")
    # ### end Alembic commands ###
