"""Make doc_id mandatory

Revision ID: 6a241a4af8da
Revises: 9f4d3a4ea3b1
Create Date: 2024-10-25 19:45:06.027367

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a241a4af8da"
down_revision: Union[str, None] = "9f4d3a4ea3b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "document_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "document_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
