"""Add QA pairs table + chunk summary to Document Table + rename content_text field

Revision ID: 946f212987e3
Revises: 426776ef44ea
Create Date: 2024-11-07 14:30:40.605609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "946f212987e3"
down_revision: Union[str, None] = "426776ef44ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qa_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "documents", sa.Column("contextualized_chunk", sa.Text(), nullable=False)
    )
    op.add_column("documents", sa.Column("chunk_summary", sa.Text(), nullable=False))
    op.drop_index(
        "idx_documents_fulltext", table_name="documents", postgresql_using="gin"
    )
    op.create_index(
        "idx_documents_fulltext",
        "documents",
        ["contextualized_chunk"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"contextualized_chunk": "gin_trgm_ops"},
    )
    op.drop_column("documents", "content_text")
    op.drop_column("documents", "extracted_question_answers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "extracted_question_answers", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "documents",
        sa.Column("content_text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        "idx_documents_fulltext",
        table_name="documents",
        postgresql_using="gin",
        postgresql_ops={"contextualized_chunk": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_documents_fulltext",
        "documents",
        ["content_text"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("documents", "chunk_summary")
    op.drop_column("documents", "contextualized_chunk")
    op.drop_table("qa_pairs")
    # ### end Alembic commands ###
