"""remove_file_id_column

Revision ID: aaa104d6c3ed
Revises: ddc3a53cac8d
Create Date: 2025-03-03 16:50:59.814301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaa104d6c3ed"
down_revision: Union[str, None] = "ddc3a53cac8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "file_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
