"""Add survey_type field to Documents

Revision ID: a41f229f5c91
Revises: 59348c8f5a37
Create Date: 2025-04-09 23:25:33.204461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a41f229f5c91"
down_revision: Union[str, None] = "59348c8f5a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("survey_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "survey_type")
    # ### end Alembic commands ###
