"""Add user_id to log table

Revision ID: 59348c8f5a37
Revises: da3e7fac6cde
Create Date: 2025-04-08 23:28:57.278002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59348c8f5a37'
down_revision: Union[str, None] = 'da3e7fac6cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_logs', 'user_id')
    # ### end Alembic commands ###
