"""remove_notes_column

Revision ID: 62342bab6861
Revises: aaa104d6c3ed
Create Date: 2025-03-05 11:34:59.706611

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62342bab6861"
down_revision: Union[str, None] = "aaa104d6c3ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
